# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

jobs:
- job: FileCreate 
  steps: 
  - script: mkdir f1
  - script: touch f1/f1
  - script: ls -lart
  - script: pwd
  - task: S3Upload@1
    inputs:
      awsCredentials: 'AWS_SANDBOX'
      regionName: 'us-east-1'
      bucketName: 'azure-devops-1'
      sourceFolder: 'f1'
      globExpressions: '**'


