variables:
  NODE_VERSION: v12.19.1
  BUILD_TARGET: clmg
  APP_NAME: clmg
  VCODE_APP_NAME: ${CLMG_VCODE_APP_NAME}
  VCODE_APP_ZIPNAME: kfhub_clmg_lib.zip
  VCODE_VERSION: ${VERACODE_WRAPPER_VERSION}
  VCODE_ID: ${VCODE_ID}
  VCODE_KEY: ${VCODE_KEY}
default:
  tags:
    - kfhub-gitlab-build
  before_script:
    - export TERM=xterm
    - nvm use ${NODE_VERSION}
    - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    - npm install jsontool@7.0.2
    - npm install @kf-products-core/kfhub_cicd
  retry:
    max: 2
    when:
      - data_integrity_failure
      - scheduler_failure
      - stale_schedule
      - stuck_or_timeout_failure
      - script_failure
      - unknown_failure
stages:
  - build
  - build_nosourcemap
  - deploy_dev
  - deploy_devint
  - deploy_pretest
  - deploy_pretestb
  - deploy_test
  - deploy_staging
  - deploy_CN
  - deploy_EU
  - deploy_US
  - veracode_scan_sandbox
  - veracode_scan
build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG =~ /--staging--deployment--\d{14}$/ || $CI_COMMIT_TAG =~ /--stage--deployment--\d{14}$/
      when: never
    - if: $CI_COMMIT_TAG =~ /--pre-staging--deployment--\d{14}$/ || $CI_COMMIT_TAG =~ /--pre-stage--deployment--\d{14}$/
      when: never
    - if: $CI_COMMIT_TAG =~ /--manual--deployment--\d{14}$/
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_TAG =~ /--[a-z]+--deployment--\d{14}$/
      when: on_success
  script:
    - npm install
    - npm run build:all ${BUILD_TARGET} ci-invoker
  artifacts:
    paths:
      - ./release
build_nosourcemap:
  stage: build_nosourcemap
  rules:
    - if: $CI_COMMIT_TAG =~ /--manual--deployment--\d{14}$/
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_TAG =~ /--pre-staging--deployment--\d{14}$/ || $CI_COMMIT_TAG =~ /--pre-stage--deployment--\d{14}$/
      when: on_success
    - if: $CI_COMMIT_TAG =~ /--staging--deployment--\d{14}$/ || $CI_COMMIT_TAG =~ /--stage--deployment--\d{14}$/
      when: on_success
  script:
    - npm install
    - npm run build:all ${BUILD_TARGET} ci-invoker no-sourcemap
  artifacts:
    paths:
      - ./release
deploy_dev:
  stage: deploy_dev
  rules:
    - if: $CI_COMMIT_TAG =~ /--manual--deployment--\d{14}$/
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_TAG =~ /--dev--deployment--\d{14}$/
      when: on_success
  script:
    - npm run deploy -- --input deploy/dev.json --only app --auto
deploy_devint:
  stage: deploy_devint
  rules:
    - if: $CI_COMMIT_TAG =~ /--manual--deployment--\d{14}$/
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_TAG =~ /--devint--deployment--\d{14}$/
      when: on_success
  script:
    - npm run deploy -- --input deploy/devint.json --only app --auto
deploy_pretest:
  stage: deploy_pretest
  rules:
    - if: $CI_COMMIT_TAG =~ /--manual--deployment--\d{14}$/
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_TAG =~ /--pretest--deployment--\d{14}$/
      when: on_success
  script:
    - npm run deploy -- --input deploy/pretest.json --only app languages --auto
deploy_pretestb:
  stage: deploy_pretestb
  rules:
    - if: $CI_COMMIT_TAG =~ /--manual--deployment--\d{14}$/
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_TAG =~ /--pretestb--deployment--\d{14}$/
      when: on_success
  script:
    - npm run deploy -- --input deploy/pretestb.json --only app languages --auto
deploy_test:
  stage: deploy_test
  rules:
    - if: $CI_COMMIT_TAG =~ /--manual--deployment--\d{14}$/
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_TAG =~ /--test--deployment--\d{14}$/
      when: on_success
  script:
    - npm run deploy -- --input deploy/test.json --only app --auto
deploy_staging:
  stage: deploy_staging
  rules:
    - if: $CI_COMMIT_TAG =~ /--manual--deployment--\d{14}$/
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_TAG =~ /--pre-staging--deployment--\d{14}$/
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_TAG =~ /--staging--deployment--\d{14}$/ || $CI_COMMIT_TAG =~ /--stage--deployment--\d{14}$/
      when: on_success
  script:
    - npm run deploy -- --input deploy/staging.json --only app --auto
deploy_US:
  stage: deploy_US
  rules:
    - if: $CI_COMMIT_TAG =~ /--manual--deployment--\d{14}$/
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_TAG =~ /--pre-staging--deployment--\d{14}$/ || $CI_COMMIT_TAG =~ /--pre-stage--deployment--\d{14}$/
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_TAG =~ /--staging--deployment--\d{14}$/ || $CI_COMMIT_TAG =~ /--stage--deployment--\d{14}$/
      when: manual
      allow_failure: true
  script:
    - npm run deploy -- --input deploy/prod-us.json --only app --auto
deploy_EU:
  stage: deploy_EU
  rules:
    - if: $CI_COMMIT_TAG =~ /--manual--deployment--\d{14}$/
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_TAG =~ /--pre-staging--deployment--\d{14}$/ || $CI_COMMIT_TAG =~ /--pre-stage--deployment--\d{14}$/
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_TAG =~ /--staging--deployment--\d{14}$/ || $CI_COMMIT_TAG =~ /--stage--deployment--\d{14}$/
      when: manual
      allow_failure: true
  script:
    - npm run deploy -- --input deploy/prod-eu.json --only app --auto
deploy_CN:
  stage: deploy_CN
  rules:
    - if: $CI_COMMIT_TAG =~ /--manual--deployment--\d{14}$/
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_TAG =~ /--pre-staging--deployment--\d{14}$/ || $CI_COMMIT_TAG =~ /--pre-stage--deployment--\d{14}$/
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_TAG =~ /--staging--deployment--\d{14}$/ || $CI_COMMIT_TAG =~ /--stage--deployment--\d{14}$/
      when: manual
      allow_failure: true
  script:
    - npm run deploy -- --input deploy/prod-cn.json --only app --auto
veracode_scan_sandbox:
  stage: veracode_scan_sandbox
  rules:
    - if: $CI_COMMIT_TAG =~ /--manual--deployment--\d{14}$/
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_TAG =~ /--pre-staging--deployment--\d{14}$/ || $CI_COMMIT_TAG =~ /--pre-stage--deployment--\d{14}$/
      when: on_success
      allow_failure: true
    - if: $CI_COMMIT_TAG =~ /--staging--deployment--\d{14}$/ || $CI_COMMIT_TAG =~ /--stage--deployment--\d{14}$/
      when: on_success
      allow_failure: true
  image: openjdk:10
  script:
    - sudo apt-get update && sudo apt-get install -y zip jq
    - zip -r ${VCODE_APP_ZIPNAME} ./src
    - wget -q -O veracode-wrapper.jar https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/${VCODE_VERSION}/vosp-api-wrappers-java-${VCODE_VERSION}.jar
    - java -jar veracode-wrapper.jar -vid ${VCODE_ID} -vkey ${VCODE_KEY} -action UploadAndScan -appname "${VCODE_APP_NAME}" -createprofile true -autoscan true -sandboxname ci-sandbox -version ${CI_COMMIT_TAG}-${APP_NAME} -filepath ${VCODE_APP_ZIPNAME}
veracode_scan:
  stage: veracode_scan
  image: openjdk:10
  rules:
    - if: $CI_COMMIT_TAG =~ /--manual--deployment--\d{14}$/
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_TAG =~ /--pre-staging--deployment--\d{14}$/ || $CI_COMMIT_TAG =~ /--pre-stage--deployment--\d{14}$/
      when: manual
      allow_failure: true
    - if: $CI_COMMIT_TAG =~ /--staging--deployment--\d{14}$/ || $CI_COMMIT_TAG =~ /--stage--deployment--\d{14}$/
      when: manual
      allow_failure: true
  script:
    - sudo apt-get update && sudo apt-get install -y zip jq
    - zip -r ${VCODE_APP_ZIPNAME} ./src
    - wget -q -O veracode-wrapper.jar https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/${VCODE_VERSION}/vosp-api-wrappers-java-${VCODE_VERSION}.jar
    - java -jar veracode-wrapper.jar -vid ${VCODE_ID} -vkey ${VCODE_KEY} -action UploadAndScan -appname "${VCODE_APP_NAME}" -createprofile true -autoscan true -version ${CI_COMMIT_TAG}-${APP_NAME} -filepath ${VCODE_APP_ZIPNAME}
